metabrainz/critiquebrainz

critiquebrainz/data/constants.py
critiquebrainz/data/model/review.py
critiquebrainz/frontend/review/views.py
critiquebrainz/ws/review/views.py
scripts/bootstrap.sh

Previous version of CritiqueBrainz used review classes for various features within the website. The problem is that these classes are not very useful and confusing. Now review_classes from critiquebrainz/data/constants.py and its' usages are removed.
My task on GCI : https://codein.withgoogle.com/dashboard/task-instances/5507485452468224/
Also git was missing in scripts/bootstrap.sh

Make ReviewClasses less confusing.

---

critiquebrainz/frontend/templates/artist.html
critiquebrainz/frontend/templates/release_group.html

Neither https://critiquebrainz.org/artist/467f69b6-8d6d-4d2c-bfad-e89adf2806ff nor https://critiquebrainz.org/release-group/1bd3ecb6-e064-3eef-a850-25eb5c0a50ee have any mention of the CoverArtArchive, but both pull in cover art from it.   
I've added some annotations about CAA on both pages.
[GCI task](https://codein.withgoogle.com/dashboard/task-instances/6387195350876160/)
[#CB-192](http://tickets.musicbrainz.org/browse/CB-192)

CB-192: Add link to Cover Art Archive on /artist and /release group

---

critiquebrainz/data/model/user.py
critiquebrainz/frontend/messages.pot
critiquebrainz/frontend/templates/review/modify/base.html
critiquebrainz/frontend/templates/review/modify/event.html

Added the note and used "fab extract_strings" to create the portable object template file(messages.pot)
Also fixed bug reported at http://tickets.musicbrainz.org/browse/CB-194

Added note for drafts not being private and fixed ISE on reviewing event without place

---

critiquebrainz/data/export_manager.py
critiquebrainz/frontend/templates/review/modify/base.html

Drafts reviews and revisions are included in the public data dumps. This should not be the case if users did not know that their drafts were not private.  #14 resolved [jira:CB-160](http://tickets.musicbrainz.org/browse/CB-160) by adding a note to warn users that drafts weren't private.
This PR resolves [jira:CB-208](http://tickets.musicbrainz.org/browse/CB-208), which attemps to solve the problem better by excluding draft reviews and revisions from the public data dumps: 
The commit messages contain detailed information about the implementation.

Exclude drafts from public dumps

---

critiquebrainz/frontend/__init__.py
critiquebrainz/frontend/apis/musicbrainz.py
critiquebrainz/frontend/release/views.py
critiquebrainz/frontend/release/views_test.py

[CB-195: Redirect cb.o/release/$R_MBID to parent cb.o/release-group/$RG_MBID](http://tickets.musicbrainz.org/browse/CB-195)

CB-195 Redirect /release/ to proper /release-group/

---

critiquebrainz/frontend/__init__.py
critiquebrainz/frontend/templates/review/entity/base.html
requirements.txt

This PR resolves the part of http://tickets.musicbrainz.org/browse/CB-123 about simply displaying reviews' languages. The work is broken up into two commits.

Display review language

---

critiquebrainz/frontend/templates/release_group.html

I added the link to the CAA in the external links of /release-group/. As the ticket stated, there was supposedly the same addition required for /artist/, but it seemed to already have been added.
http://tickets.musicbrainz.org/browse/CB-192

CB-192: Added <a> to release_group.html in External Links column

---

critiquebrainz/frontend/templates/footer.html
critiquebrainz/frontend/templates/navbar.html

This PR resolved [CB-111](http://tickets.musicbrainz.org/browse/CB-111). 505c3d3b58c69 moves the language selector to replace the “About” navbar link, and 152c94d9865c2 adds a second language selector back to the footer but makes it only visible when the navbar language selector is hidden or collapsed.

Make language selector more visible

---

critiquebrainz/frontend/external/spotify.py

Mapping page failed to load if Spotify didn't return info about an album. Now it is fixed.
[Link to the ticket](http://tickets.musicbrainz.org/browse/CB-171)

CB-171: Spotify null info returned case fixed

---

critiquebrainz/frontend/static/css/main.less

Tested on Firefox 43.0 on Ubuntu 14.04.

CB-213: Fix display of entity type labels

---

critiquebrainz/frontend/templates/mapping/spotify.html
critiquebrainz/frontend/views/mapping.py

CritiqueBrainz provides an embedded Spotify player on pages that are mapped to it in mbspotify. Mappings are created by users on CritiqueBrainz using a search interface that we have. Search gets data from Spotify using their Web API, but the only parts we use are cover art and name of the album. Now users can also see the artists that made some particular album and the release year.
[Related ticket] (http://tickets.musicbrainz.org/browse/CB-134)
Prototypes: 
1. **Artists from tracks if unavailable, date in the same line as artists and in brackets.**
2. **Artists from default artists, date in the same line as artists and in brackets.**
3. **Artists from tracks if unavailable, date in the same line as type and in brackets.**
4. **Artists from default artists, date in the same line as type …

CB-134 More information about Spotify albums on mapping page is shown now.

---

critiquebrainz/frontend/views/release.py

It seems that the gettext function wasn't even being imported in that script. Fixed

Added import of gettext in views/release.py

---

critiquebrainz/frontend/templates/review/revisions.html
critiquebrainz/frontend/views/review.py

With reviews more than 10 revisions, the "Load older revisions" button must load older revisions. For instance, in the revisions of [this](https://critiquebrainz.org/review/81f0aa06-8b9c-4490-b090-7e54614fe59e/revisions) review, load older revisions button is not working. The console error in browser showed that the load_more() function is not defined.

CB-241: Make "Load Older Revisions" button function

---

critiquebrainz/frontend/templates/footer.html

Changed documentation link TLD due to http://blog.readthedocs.com/securing-subdomains/

Changed documentation link from .org to .io

---

critiquebrainz/frontend/templates/release_group/entity.html

* Fixes a grammatical error due to a missing article.
* Adds more context to the "See all on MusicBrainz" string, which seems too ambiguous for translators on its own (see all what?). I think it reads better with "releases," anyway.

Fix a couple language issues in the MusicBrainz release group links

---

critiquebrainz/db/review.py
critiquebrainz/db/review_test.py
critiquebrainz/db/revision.py
critiquebrainz/db/revision_test.py
critiquebrainz/db/spam_report_test.py
critiquebrainz/db/users.py
critiquebrainz/db/users_test.py
critiquebrainz/db/vote.py
critiquebrainz/db/vote_test.py
critiquebrainz/frontend/views/artist.py
critiquebrainz/frontend/views/event.py
critiquebrainz/frontend/views/index.py
critiquebrainz/frontend/views/place.py
critiquebrainz/frontend/views/release_group.py
critiquebrainz/frontend/views/review.py
critiquebrainz/frontend/views/test/test_review.py
critiquebrainz/frontend/views/user.py

Functions and tests for migrating `reviews` off the ORM. Changes have been made to the `frontend` component to use the migrated code. I have added the following functions in `db/review.py` and the corresponding tests (`db/review_test.py`):
+ `get_by_id` for getting review by id.
+ `hide` and `unhide` for hiding and unhiding reviews.
+ `get_count` for review count.
+ `update` for updating a reviews info.
+ `create` for creating a review.
+ `delete` for deleting a review.
+ `list` for list reviews and filter them on various filters.
+ `get_popular` for getting popular reviews.
+ `revision.create` for creating a revision.
+ `votes` for getting votes of a revision.

CB-230: Migrate review related code off the ORM

---

admin/sql/create_extensions.sql
admin/sql/create_foreign_keys.sql
admin/sql/create_indexes.sql
admin/sql/create_primary_keys.sql
admin/sql/create_tables.sql
admin/sql/create_types.sql
critiquebrainz/data/fixtures.py
critiquebrainz/data/utils.py
manage.py

Added `create_tables.sql`, `create_extensions.sql`, `create_types.sql`, `create_primary_keys.sql`, `create_foreign_keys.sql`, `create_indexes.sql` for creating database. Also, made changes to `data/utils.py/create_tables` function for creating database.

CB-230: Create database without using ORM models

---

critiquebrainz/frontend/views/review.py

Reviews are currently not getting filtered according to entity type on browse review pages. Eg: https://critiquebrainz.org/review/?entity_type=event.

CB-257: Fix filtering reviews based on entity type

---

critiquebrainz/data/dump_manager.py
critiquebrainz/db/__init__.py
critiquebrainz/db/license.py
critiquebrainz/db/license_test.py
critiquebrainz/db/review.py
critiquebrainz/db/review_test.py

Migrated all functions i.e `public`, `import` and `json` of the `dump_manager.py` off the ORM.

CB-230: Migrate dump_manager.py off the ORM

---

critiquebrainz/frontend/__init__.py
critiquebrainz/frontend/external/musicbrainz_db/__init__.py
default_config.py
docker/docker-compose.dev.yml
docs/intro.rst

The metabrainz/musicbrainz-test-docker image is used for adding another container. The volume for the container is specified to be `data/mbdata`. On running the metabrainz/musicbrainz-test-docker image, an empty MusicBrainz database is created. Also, all the constraints are added to the empty database. For using the image for database access, we have a few options to import data:
+ Disable FK constraints by disabling triggers, import data from files and then enable triggers
+ Import data for tables sequentially by not disabling FK constraints and delaying the import for tables for which the import initially fails due to FK constraints.
+ Drop all foreign key constraints on tables and later add them.
I've implemented basic example functions `mb_importer_topo` (for topologically sorting …

CB-231: Setup for accessing MusicBrainz Database

---

docs/intro.rst

I updated the docs for focusing on a single way for setting up the MusicBrainz database. Also sent a PR for  updating the download of dumps with retries: https://github.com/metabrainz/musicbrainz-server/pull/527.

CB-231: Update docs for specifying single way of setting up MB database.

---

critiquebrainz/ws/review/views.py
critiquebrainz/ws/review/views_test.py

Fixes `AttributeError` in ws while getting revisions. Also added test `test_revision_entity_handler` for testing the ws endpoint.

CB-230: Fix error in getting revisions in ws and add test.

---

critiquebrainz/frontend/external/musicbrainz_db/__init__.py
critiquebrainz/frontend/external/musicbrainz_db/exceptions.py
critiquebrainz/frontend/external/musicbrainz_db/helpers.py
critiquebrainz/frontend/external/musicbrainz_db/includes.py
critiquebrainz/frontend/external/musicbrainz_db/place.py
critiquebrainz/frontend/external/musicbrainz_db/serialize.py
critiquebrainz/frontend/views/place.py
requirements.txt

Use direct database access for entity `place`. I have added functions `entity_relation_helper` and `get_place_by_id` for fetching information regarding `place`.

CB-231: Use direct database access for entity: place

---

critiquebrainz/frontend/templates/review/browse.html

Fixes filtering reviews which presently does not work on `Next` or `Previous` link to see more reviews on `/review` pages.

CB-257: Fix review filtering in browse-review pages.

---

critiquebrainz/db/review.py
critiquebrainz/db/review_test.py
critiquebrainz/frontend/views/event.py
critiquebrainz/frontend/views/place.py
critiquebrainz/frontend/views/release_group.py
critiquebrainz/ws/review/views.py

- Currently 'rating' is used as difference in +/- votes to list and determine
popular reviews
- Changed it to 'net_votes' to avoid conflict with entity rating
I didn't change it to 'popularity' because we may change the criteria to determine popular reviews after the rating system has been implemented

Update current usage of the term 'rating'

---

critiquebrainz/frontend/external/musicbrainz_db/helpers.py
critiquebrainz/frontend/external/musicbrainz_db/place.py

Updated `entity_relation_helper` and `get_place_by_id` to fetch info for multiple entities. Function `fetch multiple places` can be used to fetch info of multple places.

CB-231: Update db access function and helpers for multiple entities.

---

critiquebrainz/frontend/external/musicbrainz_db/place.py
critiquebrainz/frontend/external/musicbrainz_db/serialize.py
critiquebrainz/frontend/external/musicbrainz_db/utils.py

Reduces the number of db queries for entity: `place`. Using `joinedload` for `area` and `type` saves two queries. Also, added `get_entities_by_gid` which reduces the number of queries to fetch many places by `gid`.(to max 3 queries (in case of redirected entities, otherwise 1)). Also, fixes fetching entities for redirected mbids. A single `fetch_multiple_places` method now makes atmost 7 queries (4 for relationships + 3 for fetching all places(at max)) (for any number of `entity-gids`). 
I will also later update the tests for checking on the number of queries.

CB-231: Reduce db queries for entity: place

---

critiquebrainz/frontend/external/musicbrainz_db/place.py
critiquebrainz/frontend/external/musicbrainz_db/release_group.py
critiquebrainz/frontend/external/musicbrainz_db/utils.py
critiquebrainz/frontend/views/place.py
critiquebrainz/frontend/views/release_group.py

Due to sqlalchemy's `autoflushing`, it issues an `update` query while modifying redirected entity's `gid` field and this issue is raised https://sentry.metabrainz.org/share/issue/342e32363535/. I've updated the function `get_entities_by_gids` for fixing this. Eg. https://critiquebrainz.org/release-group/820ba931-840d-45f1-97ed-0cceaff26da0

Fix ISE on entity pages involving MBID redirects

---

critiquebrainz/db/review.py

Modified the criteria for popular_reviews.
Consider only those reviews with text for popular_reviews. lt doesn't seem right to display reviews with only rating on the index page.

Don't include reviews without text into the popular list

---

critiquebrainz/frontend/external/musicbrainz_db/includes.py
critiquebrainz/frontend/external/musicbrainz_db/release.py
critiquebrainz/frontend/external/musicbrainz_db/serialize.py
critiquebrainz/frontend/external/musicbrainz_db/test_data.py
critiquebrainz/frontend/external/musicbrainz_db/tests/helpers_test.py
critiquebrainz/frontend/external/musicbrainz_db/tests/release_test.py
critiquebrainz/frontend/external/soundcloud.py
critiquebrainz/frontend/templates/release_group/entity.html
critiquebrainz/frontend/views/release.py
critiquebrainz/frontend/views/release_group.py
critiquebrainz/frontend/views/test/test_release.py

Used db access for entity: `release`. The work for using db for releases is complete but the tests (failing) are remaining. Will rebase this when I finish the `test_db` PR.

CB-231: Use direct db access for entity: release

---

CONTRIBUTING.md

Since we now have a repository with common contribution guildelines for
MetaBrainz projects it doesn't make much sense to copy them around. It's
much easier to reference that repository and than keeping
CONTRIBUTING.md files in sync in all the projects.

Reference MetaBrainz-wide contribution guidelines

---

critiquebrainz/frontend/external/musicbrainz_db/artist.py
critiquebrainz/frontend/external/musicbrainz_db/includes.py
critiquebrainz/frontend/external/musicbrainz_db/release_group.py
critiquebrainz/frontend/external/musicbrainz_db/serialize.py
critiquebrainz/frontend/external/musicbrainz_db/tests/artist_test.py
critiquebrainz/frontend/external/musicbrainz_db/tests/helpers_test.py
critiquebrainz/frontend/external/musicbrainz_db/tests/release_group_test.py
critiquebrainz/frontend/external/relationships/artist.py
critiquebrainz/frontend/templates/artist/entity.html
critiquebrainz/frontend/views/artist.py
critiquebrainz/frontend/views/test/test_artist.py

Added functions for fetching artists information from mb database. 
Tasks remaining:

CB-231: Retrieve artist data directly from the MB database

---

critiquebrainz/db/__init__.py
critiquebrainz/db/avg_rating.py
critiquebrainz/db/avg_rating_test.py
critiquebrainz/db/review.py
critiquebrainz/db/review_test.py
critiquebrainz/db/revision.py
critiquebrainz/db/revision_test.py
critiquebrainz/db/vote_test.py

Now, the whole CB codebase can use the scale of 1-5 for ratings.
For storage, ratings will be converted to the scale 0-100 right before inserting them into the database.

Constrain rating storage conversions within one module

---

critiquebrainz/frontend/__init__.py
critiquebrainz/frontend/external/musicbrainz_db/entities.py
critiquebrainz/frontend/external/musicbrainz_db/serialize.py
critiquebrainz/frontend/external/musicbrainz_db/utils.py
critiquebrainz/frontend/templates/review/browse.html
critiquebrainz/frontend/views/review.py
critiquebrainz/frontend/views/test/test_review.py

Modifed `jinja2` filter for fetching entities by id and added code for retrieving data directly from database for browse review (`/review`) pages.

CB-231: Retrieve data from database directly for browse review pages

---

critiquebrainz/frontend/external/musicbrainz_db/serialize.py

Fixes this `AttributeError` when medium format is `None`.
```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/werkzeug/wsgi.py", line 660, in __call__
return app(environ, start_response)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
response = …
```

Fix AttributeError when Medium has no format

---

critiquebrainz/db/__init__.py

Fixes the SCHEMA_VERSION (of the CB database) to the current version (based on the number of schema changes in the past).

Change schema version to 8

---

docker/Dockerfile.test
manage.py

As decided in discussions [here](https://github.com/metabrainz/critiquebrainz/pull/164#issuecomment-354597289), it is good to create db tables in test container before running tests (and not just rely on pytest's  `setUp()` method .

CB-276: Initialize db and create tables in test container before running tests

---

critiquebrainz/frontend/views/review.py
critiquebrainz/frontend/views/test/test_review.py

I accidently stumbled across this bug and I thought I would fix it, since it was pretty simple. What was happening was that in these lines in `views/review.py`, in the `create` function:
```python
review = db_review.list_reviews(user_id=current_user.id, entity_id=entity_id)[0] # here's the main problem
if review:
flash.error(gettext("You have already published a review for this entity!"))
return redirect(url_for('review.entity', id=review["id"]))
```
The first line depends on `db_review.list_reviews` returning a list of reviews straight away. However, `list_reviews` has either since been changed or this line was just a mistake, because `list_reviews` returns a tuple of `(review, count)` (which is weird - returning a list of reviews, you could just get their count using `len(reviews)`, but …

Fix bug when trying to write a duplicate review

---

docker/docker-compose.dev.yml
docs/intro.rst

Improvement in the documentation
For the users that have enabled SELinux on their OS (inbuilt in some OS):
If they run `$ docker-compose -f docker/docker-compose.dev.yml run musicbrainz_db`, following error might occur:
python3: can't open file 'manage.py': [Errno 13] Permission denied
If they further run `$ docker-compose -f docker/docker-compose.dev.yml run critiquebrainz python3 \
manage.py init_db --skip-create-db` following error might occur: 
chown: cannot read directory ‘/var/lib/postgresql/data/pgdata’: Permission denied

Add documentation for disabling SELinux

---

critiquebrainz/frontend/templates/navbar.html

This pull request is the bug fix on error pages. 
It adds the missing sign in button on error pages.
Dropdown menu is purposely not provided as it is mentioned in the comments (https://github.com/metabrainz/critiquebrainz/blob/master/critiquebrainz/frontend/templates/navbar.html#L19) that while loading, user info might fail and page will not render.

CB-225: Add Sign in button on error pages

---

critiquebrainz/frontend/templates/review/modify/base.html
critiquebrainz/frontend/views/review.py
requirements.txt

[Jira ticket.](https://tickets.metabrainz.org/browse/CB-271)
Using the `langdetect` library. It supports all of the languages that CB has in its languages menu on the navbar, plus many more. `langdetect` is already well tested, so I didn't really add any tests for this feature. But if needed I can.

CB-271: Automatically detect the language of reviews

---

docs/intro.rst

This pull request is for the bug fix in the documentation.
If the user runs `$ docker logs -f critiquebrainz_web_test_1`, following error occurs:
Error: No such container: critiquebrainz_web_test_1

Change container name in Testing

---

critiquebrainz/frontend/external/spotify.py
critiquebrainz/frontend/external/spotify_test.py

Fix missing suggestions after caching and added a test for checking cached spotify results. Since the same list object was passed to the function `get_multiple_albums` (in `spotify.py`), `album_ids` were deleted from the original object and cached results showed no suggestions instead.

CB-280: Fix Spotify mapping page suggestions

---

docs/intro.rst

The installation guidelines of CritiqueBrainz were outdated and were very confusing. So its need to be updated. Ticket:- https://tickets.metabrainz.org/browse/CB-277

CB-277: Update the installation guidelines

---

critiquebrainz/frontend/templates/search/selector.html

In this patch, the user does not need to check the radio button, by clicking on the row itself the corresponding radio button gets checked.

CB-252: Make whole row selectable in search results

---

critiquebrainz/frontend/views/moderators.py

Earlier, gravatar_url() was generating a new hash at the time of creating the dictionary of moderators is which was creating the error. Now, in this PR instead of generating the new hash, it has been replaced with existing generated avatar_url which is fixed for the user. 
P.S. - The change is not tested as I didn't have a working dev environment with a database to test my changes. So I don't know whether this is a proper fix for the bug or not. :)

CB-242: Incorrect gravatars are shown on /moderators

---

critiquebrainz/data/dump_manager.py
critiquebrainz/data/utils.py
critiquebrainz/db/dump_manager_test.py
docker/Dockerfile.test

Added tests for `dump_manager.py` functions. The tests fail presently. `reset_db()` fails and closes connection to the db. This needs to be fixed.

CB-286: Add tests for dump manager functions

---

admin/schema_changes/13.sql
admin/sql/create_tables.sql
critiquebrainz/db/__init__.py
critiquebrainz/frontend/forms/comment.py
critiquebrainz/frontend/views/comment.py
critiquebrainz/frontend/views/test/test_comment.py

Changed SQL and Comment Form to reject empty comments.

CB-321: No empty comments

---

critiquebrainz/frontend/error_handlers.py
critiquebrainz/frontend/templates/macros.html
critiquebrainz/frontend/templates/mapping/list.html
critiquebrainz/frontend/templates/mapping/spotify.html
critiquebrainz/frontend/views/mapping.py
critiquebrainz/frontend/views/test/test_mapping.py

*  Added tests for Spotify mapping frontend
*  Made `sentry_event_id` optional for error handlers
*  Along with parsing release year from `first-release-date`, now Spotify mapping templates will also use `first-release-year`.
*  Changed the name of view function which adds Spotify mappings, from just `spotify` to `spotify_add`.
*  Improved checking while parsing the supplied Spotify URI.
* Other small bugs.

CB-282: Spotify mapping tests

---

critiquebrainz/frontend/external/spotify.py
critiquebrainz/frontend/external/spotify_test.py
critiquebrainz/frontend/views/mapping.py

* Added functionality to check whether the access tokens in cache are expired, and fetch new tokens in that case
* Rewrite tests for Spotify module

CB-338: Check for expired access token

---

admin/schema_changes/14.sql
admin/schema_changes/15.sql
admin/sql/create_types.sql
critiquebrainz/db/__init__.py
critiquebrainz/db/moderation_log.py
critiquebrainz/db/moderation_log_test.py
critiquebrainz/frontend/templates/log/action.html
critiquebrainz/frontend/templates/log/log_results.html
critiquebrainz/frontend/templates/review/entity/base.html
critiquebrainz/frontend/templates/user/base.html
critiquebrainz/frontend/views/review.py
critiquebrainz/frontend/views/test/test_review.py
critiquebrainz/frontend/views/test/test_user.py
critiquebrainz/frontend/views/user.py

* If a review is not hidden, `Hide this review` button is shown to the moderator. Similarly, if the review is hidden, `Unhide this review` button is shown.
* A user cannot hide or unhide their review even if the user is a moderator. In this case, only some other moderator can take these actions (and is shown hide/unhide button).

CB-326: Hide and Unhide button for moderators on entity review page

---

critiquebrainz/frontend/templates/event/entity.html
critiquebrainz/frontend/templates/macros.html
critiquebrainz/frontend/templates/release_group/entity.html
critiquebrainz/frontend/views/event.py
critiquebrainz/frontend/views/release_group.py

Checks if event or release group have URL relationships of type "review," and displays the links to these reviews. Looking forward to feedback.
https://tickets.metabrainz.org/browse/CB-351

CB-351: Link external reviews imported from MusicBrainz

---

critiquebrainz/data/dump_manager.py
critiquebrainz/db/dump_manager_test.py
critiquebrainz/db/vote.py
critiquebrainz/db/vote_test.py

Additions -
* Support for adding `vote` table contents to public dumps
* Support for importing `vote` to db from public dumps

CB-348: Add votes to dumps

---

critiquebrainz/db/review.py

Reset cache when any of the reviews is deleted from the popular reviews. It's at max 6 reviews, so it shouldn't be much of load.

Reset cache when review is deleted of the popular reviews

---

critiquebrainz/frontend/static/styles/main.less
critiquebrainz/frontend/templates/review/entity/base.html
critiquebrainz/frontend/templates/review/entity/comments.html
critiquebrainz/frontend/views/comment.py
critiquebrainz/frontend/views/test/test_comment.py

Changes/additions summary:
* Separate template for comments
* Added JavaScript for dynamically displaying comment edit form when a user clicks on the comment edit button.
* Added `comment.edit` view

CB-305: Allow users to edit comments

---

admin/schema_changes/16.sql
admin/schema_changes/17.sql

This needs to be done so that each schema change can be run
independently on the main database.
cc @spellew, please take a look.

Move label schema change to different schema change script

---

README.md
develop.sh
docker/docker-compose.dev.yml
docker/docker-compose.test.yml
docs/intro.rst
test.sh

When following the setup instructions some things didn't work
* Postgres docker image now doesn't do trust auth by default, set the env variable
* New musicbrainz db test image didn't include bzip2 (https://github.com/metabrainz/musicbrainz-server/pull/1621)
Also add `develop.sh` to make more consistent with other brainzes, and update installation documentation to include it.

Setup updates

---

package-lock.json
package.json

CB-366
The most recently released version of this library doesn't support the most recent jquery, however the latest version on github does. Use this until a new release is made.

CB-366: Use a git revision of bootstrap-rating-input for jquery compatibility

---

critiquebrainz/frontend/static/styles/main.less

I just changed the z-index of the 2 badges that show above the cover art. I think this is how it was supposed to work, but previously it was just luck that the items showed above the cover art due to their implicit z-index based on the code layout

CB-360: Make labels on album image always appear above the cover art

---

package.json

The current UI components need to rewritten to work correctly with Bootstrap 4. Hence, using Bootstrap 3 till then.

CB-374: Entity selection tabs don't change when clicked

---

critiquebrainz/ws/review/views.py
critiquebrainz/ws/review/views_test.py

Check for the created parameter and map it to to published_on for backward compatibility.
JIRA: CB-376

CB-376: Breaking change in API (created => published_on)

---

critiquebrainz/frontend/forms/review.py
critiquebrainz/frontend/views/review.py

There are two things about the issue in question:-
1) Not a valid choice issue. This occurs because of the default value of the Flask Validator. However, the specific message that should be displayed for the validation failure has an extra Not a Valid Choice message. I checked the WTF forms docs and they [recommend ](https://wtforms.readthedocs.io/en/2.3.x/validators/#wtforms.validators.DataRequired) that `InputRequired` be used unless there is a specific reason to use `DataRequired`. Using, `InputRequired` also fixes the issue.
However, there are other places in the codebase where `DataRequired` is used. Do we want to change those to `InputRequired` as well ?
2) Changing the _exclamation_ to _period_ is simple. But a [livegrep](http://livegrep.metabrainz.org/search/livegrep?q=file%3A.py%2 …

CB-380: "Write a review" error messages don't give any context

---

critiquebrainz/db/review.py
critiquebrainz/db/revision.py

It might be possible that there may be other uses or potential use case
for creating a revision in a separate transaction. Hence, added the
connection as an optional parameter. To enforce the creation in the
same transaction we can make the parameter mandatory.
JIRA: CB-382

CB-382: You can sometimes create a review without a revision

---

critiquebrainz/db/statistics_test.py
critiquebrainz/frontend/external/musicbrainz_db/artist.py
critiquebrainz/frontend/external/musicbrainz_db/event.py
critiquebrainz/frontend/external/musicbrainz_db/label.py
critiquebrainz/frontend/external/musicbrainz_db/place.py
critiquebrainz/frontend/external/musicbrainz_db/release.py
critiquebrainz/frontend/external/musicbrainz_db/release_group.py
critiquebrainz/frontend/external/musicbrainz_db/tests/test_cache.py
critiquebrainz/frontend/external/musicbrainz_db/work.py

Use both entity type and mbid as cache key
JIRA: CB-369

CB-369: Write a review page shows incorrect information depending on if the item is a work or artist

---

critiquebrainz/frontend/__init__.py
critiquebrainz/frontend/forms/review.py
critiquebrainz/frontend/forms/utils.py
critiquebrainz/frontend/templates/search/selector_results.html

1) Bugfix for showing work title in search results
2) Due to some reason, the language selector for writing a review was using pycountry as a fallback if babel could not resolve the Locale. However, while displaying the language name on the view review page only babel was being used. pycountry is not added as a fallback in this case as well. This fixes CB-393.

Miscellaneous Bug Fixes 

---

critiquebrainz/frontend/external/musicbrainz_db/label.py
critiquebrainz/frontend/external/musicbrainz_db/test/test_cache.py

In 47a6164bb0 (#304) we added `unknown_entities_for_missing=True` to calls to the BU musicbrainz db methods, but for some reason forgot to update the tests.
Also missing was this flag on Label, add it.

Update tests for unknown_entities_for_missing=True fix

---

.dockerignore

Patterns in the `.dockerignore` file are incorrectly following `.gitignore` format.
The main difference is that root directory `/` is implicit in `.dockerignore` format.
See https://docs.docker.com/engine/reference/builder/#dockerignore-file for reference.
This leads to not ignoring a bunch of files when building Docker images.
It can make Docker images to be larger than necessary or to contain unintended data.
* Do not rely on defaults which are different from `.gitignore` syntax by explicitly prepending with `/` to match from the root directory only (default) or with `**/` to match from any subdirectory (and from the root directory too).
* Append an ending `/` to specify when ignoring directories
* Extend some patterns to match more actual and potential files: `.gitattributes`, …

Fix ignoring some files when building Docker images

---

critiquebrainz/frontend/external/musicbrainz_db/release_group.py

Release group caching is creating load problems. Disable it for now to diagnose issues.

Disable release-group caching

---

docker/beta/uwsgi/uwsgi.ini
docker/prod/uwsgi/uwsgi.ini

This does nothing except fill up tens to hundreds of gigabytes of logs,
and isn't needed.
UWSGI logs each request, in the form 
> [pid: 343|app: 0|req: 678/3082] 93.213.240.171 () {38 vars in 637 bytes} [Mon Feb  1 15:42:51 2021] GET /a5a41a8a-9eb8-4d89-b831-c3b3636ee55c/low-level => generated 52243 bytes in 14 msecs (HTTP/1.1 200) 10 headers in 411 bytes (1 switches on core 0)
This fills up docker logs (tens to hundreds of GB), and we don't use any of it
Disable uwsgi request logging (yes, the config option is 'disable-logging', but this is only request logging, not generic logging)

Disable uwsgi request logging

---

requirements.txt

Once metabrainz/brainzutils-python#45 is merged, BU will use open ended versions. To make sure we use desired versions, pin the versions in downstream projects.
The BU PR must be merged before this PR and the requirements.txt must be updated to use the new release of BU.

Pin package versions and upgrade brainzutils

---

critiquebrainz/ws/review/test/views_test.py
critiquebrainz/ws/review/views.py

This PR fixes a small global variable bug that caused the publish review endpoint to return an error when the review's "is_draft" was set to false.

Fix post review API

---

.github/workflows/tests.yml

The CritiqueBrainz Deploy Image action was repeatedly failing to build the production image. Adding a job to run build the production image if tests pass. We have found a similar action to be very useful in LB.

Add job to build production image if tests pass

---

Dockerfile

Do not know what the issue is with the existing Dockerfile but doing what we do in LB should hopefully fix it.

Fix PG client in CB - Attempt 2

---

critiquebrainz/ws/parser.py

If the input was already an int, it would not have isdigit method and thus raise an error. Hence, doing the check in another way.

Fix error in int argument parsing

---

critiquebrainz/frontend/login/provider.py
critiquebrainz/frontend/views/login.py

Identified in https://sentry.metabrainz.org/metabrainz/listenbrainz/issues/145812/?environment=production&referrer=alert_email
Although it doesn't happen in a normal successful oauth flow, there are some cases where a manually constructed URL with an invalid code parameter could cause an uncaught exception.
Handle the situation where:
* the auth code isn't valid on the musicbrainz end, therefore returning an error message
* the response from musicbrainz isn't valid json

Gracefully handle errors due to invalid oauth codes

---

Dockerfile
docker/Dockerfile.dev

Apparently, an encrypt cert has expired and we are unable to do the local setup. I think this is fair in terms of local setup and we can look for permanent solutions in the Dockerfile.

Permanent fix for certificate verification

---

critiquebrainz/frontend/templates/review/modify/artist.html
critiquebrainz/frontend/templates/review/modify/event.html
critiquebrainz/frontend/templates/review/modify/label.html
critiquebrainz/frontend/templates/review/modify/place.html
critiquebrainz/frontend/templates/review/modify/recording.html
critiquebrainz/frontend/templates/review/modify/release_group.html
critiquebrainz/frontend/templates/review/modify/work.html
critiquebrainz/frontend/views/review.py

CB-367: Review page doesn't link to the detail page of the entity. 

---

critiquebrainz/frontend/templates/review/modify/edit.html
critiquebrainz/frontend/views/review.py

CB-399 Title doesn't show on edit page for some reviews

---

consul_config.py.ctmpl
critiquebrainz/frontend/templates/base.html
critiquebrainz/frontend/templates/sharing.html
custom_config.py.example

- Google Analytics has been disabled for a long time (or was never enabled?) using configuration. Disabled here means that the code to render GA wasn't send to the browser. No reason to keep this unused code.
- Google+ was discontinued a few years so removing the sharing button for it. It does not render anything currently anyway.

Remove unused code for Google Analytics and Google+

---

docker/docker-compose.dev.yml
docs/intro.rst

Bind postgres ports to 127.0.0.1 so that they're not exposed to the world if the host has a public IP address: https://github.com/metabrainz/guidelines/blob/f04bafbd3b081b24f6271b546ada47d84586e800/Docker.md#publishing-ports
Use port 8200, [close to ListenBrainz' 8100](https://github.com/metabrainz/listenbrainz-server/pull/1781), and not overlapping with 80, which may be used by different services on the same host

Update docker-compose port configuration

---

critiquebrainz/frontend/templates/footer.html
docs/intro.rst

As most browsers now don't have a built-in ftp client

Switch to http-hosted location for CB dumps

---

critiquebrainz/frontend/forms/comment.py

CB-420 surfaced that currently validation of comment input isn't working.
In short, we generate a hidden input textarea with the `required` attribute.
The textarea being both hidden and required causes some issues with native browser validation hints.
By using the Length validator instead of InputRequired, we conserve the intended mechanism without the textarea having a `required` prop.
Trying to post a comment with no content results in the expected error message:

[CB-420]: Fix comment input

---

.github/workflows/push-dev-image.yml

The current Github Actions workflow we use to deploy development Docker images allows us to select a branch or tag from this repo, but not PRs that are created from a forked repo.
With these modifications we can target the ref of the pull request even if it was created from a forked repo.
See also  https://github.com/metabrainz/listenbrainz-server/pull/1928

GH actions: deploy Docker images from PRs

---

critiquebrainz/frontend/templates/work/entity.html

On the work page, the list of recordings was not showing links. This issue was because the anchor tag was commented out in the template file.

Fix links for recordings not showing

---

critiquebrainz/frontend/templates/log/action.html
critiquebrainz/frontend/templates/reports/reports_results.html
critiquebrainz/frontend/templates/review/report.html

At some places, the entity_details filter is missing the entity_type parameter which causes the template to error. encountered while trying to hide a review.

Fix invalid use of entity_details filter

---

critiquebrainz/frontend/templates/log/action.html
critiquebrainz/frontend/templates/reports/reports_results.html
critiquebrainz/frontend/templates/review/report.html
critiquebrainz/frontend/views/review.py
critiquebrainz/frontend/views/test/test_review.py

[CB-330] 'Review has been hidden' message is shown twice when moderator hides a review.

CB-330 Removed duplicate flash messages

---

critiquebrainz/frontend/templates/recording/entity.html

A single common element can replace the rating script on all the pages. The commit https://github.com/metabrainz/critiquebrainz/commit/8f8f1e13eec2ca1999f47935925847a6d98c9c73 replaced all the rating script to a common element but missed out the script on the recording page.

CB-419: Refactor entity ratings form

---

critiquebrainz/frontend/templates/review/entity/work.html
critiquebrainz/frontend/views/artist.py
critiquebrainz/frontend/views/work.py

Found due to errors reported in sentry (the urls were accessed by bots, so likely not a huge issue)

Fix some incorrect url_for definitions

---

critiquebrainz/db/spam_report.py
critiquebrainz/frontend/templates/reports/reports_results.html
critiquebrainz/frontend/templates/review/entity/place.html
critiquebrainz/frontend/templates/review/report.html

There were bugs on the reports page that caused errors when a review of a non-releasegroup entity was reporterd

Show reports for entities other than release groups

---

critiquebrainz/frontend/forms/profile_apps.py
critiquebrainz/frontend/views/test/test_profile_apps.py

The callback URL is used in an `<a href>` on the oauth permissions page in
the "deny" button, making it possible for someone to craft a URL that
could redirect a user to a malicious page. Prevent this by requring the
callback URL to refer to properly formatted URL.
The homepage url is not checked, but this uses target="_blank", which
causes browsers to block it when opening the link.

Only allow http/s protocols in an oauth application's callback URL

---

critiquebrainz/frontend/static/styles/main.less
critiquebrainz/frontend/templates/event/entity.html
critiquebrainz/frontend/templates/review/entity/event.html
critiquebrainz/frontend/templates/review/entity/place.html
critiquebrainz/frontend/templates/search/index.html
critiquebrainz/frontend/templates/search/results.html

* Always show a disambiguation if it exists, and make it `<small>`
* Always make the first column of search results 50% wide. Search results are 4 or 5 columns wide, the other fields fit in the other 50%
* Add a link to the Place on the search results for an event
* Fix some checks for undefined data in templates
Before
After
@MonkeyDo tagging you for css check - I decided to just add a new class for it instead of repeating a `style` attribute, we don't have any react or embedded css, so just adding it to a section in the main less file.

Update search results view

---

critiquebrainz/ws/review/test/views_test.py
critiquebrainz/ws/review/views.py

By default the reviews list endpoint had no sort, which meant that we weren't sending any `ORDER BY` clause to the database. Update to always include a default sort if it's not set.

CB-429: API: Default sort by published_on desc if no sort params provided

---

critiquebrainz/ws/review/test/views_test.py
critiquebrainz/ws/review/views.py

There are 9 query parameters that can choose the reviews returned by the WS list reviews endpoint. Currently, entity_type is not considered in the cache which often causes wrong responses to be returned when entity type query param is specified.

Fix invalid cache key for WS list reviews

---

.readthedocs.yaml
docs/requirements.txt

Use same python version as prod in building docs. Also, update dependency versions.
https://readthedocs.org/projects/critiquebrainz/builds/17529003/

Add basic .readthedocs.yaml and update deps versions

---

critiquebrainz/frontend/external/bookbrainz_db/edition_group.py
critiquebrainz/frontend/templates/bb_edition_group/entity.html
critiquebrainz/frontend/templates/review/entity/bb_edition_group.html

This PR does the following: 
1. Adds a title for Edition Group's page and its reviews's page
2. Fixes typo

Add Title for Edition Group's page

---

critiquebrainz/ws/review/test/views_test.py
critiquebrainz/ws/review/views.py

* Return average ratings for entity if the entity_id is given
* Add parameter to include the metadata for the entities

CB-437: Add entity metadata to review get endpoints

---

CONTRIBUTING.md
README.md
critiquebrainz/frontend/templates/index/about.html
critiquebrainz/frontend/templates/index/index.html
docs/index.rst

This PR updates text to Include BookBrainz URLs in the docs and README.

Update Text to Include BookBrainz URL

---

critiquebrainz/db/review.py
critiquebrainz/frontend/babel.cfg
critiquebrainz/frontend/babel.py
critiquebrainz/frontend/views/user.py
critiquebrainz/ws/__init__.py
critiquebrainz/ws/review/test/views_test.py
critiquebrainz/ws/review/views.py

CB-444: API error messages are music-specific

---

critiquebrainz/frontend/views/index.py

CB-439
Reviews can be either text, a rating, or both.
In my experience, looking at the recent reviews list on the homepage is annoying if you click through to some new ones and see that they're only ratings.
In order to make the list of reviews more useful, only show ones that have actual text reviews.

CB-439 (I): Only include text reviews on front page recent reviews

---

critiquebrainz/frontend/views/comment.py
critiquebrainz/frontend/views/index.py
critiquebrainz/frontend/views/markdown.py
critiquebrainz/frontend/views/review.py
critiquebrainz/frontend/views/test/test_markdown.py
requirements.txt

Because we allow users to write links in reviews and comments, we should mark them as rel=nofollow so that any spam links that might come through don't negatively affect CB's search ranking
I didn't include [noreferrer](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noreferrer) (or noopener) in this case, I'm not sure if it's strictly necessary as well, any thoughts @amCap1712?

CB-438: add rel=nofollow to links in reviews

---

Dockerfile

(copied from https://github.com/metabrainz/listenbrainz-server/commit/1ce3af2cacb108b15cf044def385084fafbffe2b)
PostgreSQL doesn't currently support xenial.
1. This approach will eliminate the need to change repository source names every time the base image is updated to a newer version.
2. This approach is mentioned on PostgreSQL docs - https://www.postgresql.org/download/linux/ubuntu/
Output of `cat /etc/apt/sources.list.d/pgdg.list`: `deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main 12` which is correct for current base image.

Dockerfile: Install postgresql-client from current base image repo

---

critiquebrainz/db/comment.py
critiquebrainz/db/moderation_log.py
critiquebrainz/db/review.py
critiquebrainz/db/spam_report.py
critiquebrainz/db/statistics.py
critiquebrainz/db/user.py
critiquebrainz/db/users.py
critiquebrainz/frontend/templates/log/action.html
critiquebrainz/frontend/templates/log/log_results.html
critiquebrainz/frontend/templates/macros.html
critiquebrainz/frontend/templates/moderators/moderators.html
critiquebrainz/frontend/templates/navbar.html
critiquebrainz/frontend/templates/reports/reports_results.html
critiquebrainz/frontend/templates/review/entity/base.html
critiquebrainz/frontend/templates/review/revisions.html
critiquebrainz/frontend/templates/statistics/stats.html
critiquebrainz/frontend/templates/user/base.html
critiquebrainz/frontend/templates/user/reviews.html
critiquebrainz/frontend/views/profile.py
critiquebrainz/frontend/views/review.py
critiquebrainz/frontend/views/test/test_artist.py
critiquebrainz/frontend/views/test/test_comment.py
critiquebrainz/frontend/views/test/test_profile.py
critiquebrainz/frontend/views/test/test_profile_apps.py
critiquebrainz/frontend/views/test/test_review.py
critiquebrainz/frontend/views/test/test_statistics.py
critiquebrainz/frontend/views/test/test_user.py
critiquebrainz/frontend/views/user.py
critiquebrainz/ws/user/test/views_test.py
critiquebrainz/ws/user/views.py

Identify users by username (if they are linked with MB account) and by UUID (if they are not linked with MB account).

CB-416: Identify users by musicbrainz username, not uuid

---

critiquebrainz/frontend/forms/profile.py
critiquebrainz/frontend/views/review.py
requirements.txt

This is needed for https://github.com/metabrainz/critiquebrainz/pull/417.
Unselected radio field results in the value of the field being 'None' not None. This is fixed in newer versions. In newer versions, a few imports have changed and email_validators needs to be added a dependency separately to use EmailField.
Newer version of WTForms do not cache form.errors so each call to errors returns a new dict. Form level validation should instead be performed by appending errors to form.form_errors as shown in this commit. https://github.com/wtforms/wtforms/commit/22636b55eda9300b549c8bbaae6f9ae31595d445

 Update WTForms

---

admin/schema_changes/23.sql
admin/sql/create_indexes.sql

With #403, we perform a check as `"user".id::text = :user_ref`. `:user_ref` can be a username or a uuid, therefore we need to cast "user".id to text so that the comparison succeeds without error in case :user_ref is a username. Casting to text, however disables the use of any uuid indexes we may have on "user".id so add a new index on "user".id::text.
```
critiquebrainz_db=> begin;
BEGIN
critiquebrainz_db=> explain analyze select * from "user" where id::text = 'amCap1712';
QUERY PLAN
---------------------------------------------------------------------------------------------------
Seq Scan on "user"  (cost=0.00..77.18 rows=13 width=78) (actual time=2.317..2.317 rows=0 loops=1)
Filter: ((id)::text = 'amCap1712'::text)
Rows Removed by Filter: 2631
Planning Time: 0.069 ms
Execution Time: …
```

Add index on "user".id::text

---

critiquebrainz/db/users.py
critiquebrainz/frontend/login/provider.py
critiquebrainz/frontend/views/test/test_login.py
requirements.txt

We already do this in LB, implementing the same for CB. However, CB also has a display name field as well. If the display name has been changed to something else than the old musicbrainz id, update it as well otherwise let it remain set to the custom name.

Update musicbrainz_id on login

---

critiquebrainz/frontend/external/bookbrainz_db/common_entity.py
critiquebrainz/frontend/external/bookbrainz_db/test/common_entity_test.py
critiquebrainz/frontend/templates/artist/entity.html
critiquebrainz/frontend/templates/bb_author/entity.html
critiquebrainz/frontend/templates/bb_literary_work/entity.html
critiquebrainz/frontend/templates/work/entity.html
critiquebrainz/frontend/views/artist.py
critiquebrainz/frontend/views/bb_author.py
critiquebrainz/frontend/views/bb_literary_work.py
critiquebrainz/frontend/views/work.py

This PR unifies reviews for Artist-Author, Work-Literary Work having relationship between them.

Unify reviews for Common MB-BB entities

---

critiquebrainz/db/review.py
critiquebrainz/db/test/review_test.py
critiquebrainz/db/user.py
critiquebrainz/frontend/templates/macros.html

A user's musicbrainz user, or user_ref isn't private data, and show should always show when rendering a user object.
For security, don't pass email address to the template

Use confidential=False when showing data in template

---

critiquebrainz/frontend/templates/index/about.html

Updated the guideline section to include community agreed upon LLM/’AI’ usage guidelines.

CB-459: Add LLM guidelines

---

critiquebrainz/db/comment.py
critiquebrainz/frontend/templates/index/about.html
critiquebrainz/frontend/templates/index/guidelines.html
critiquebrainz/frontend/templates/log/action.html
critiquebrainz/frontend/templates/macros.html
critiquebrainz/frontend/templates/mapping/spotify.html
critiquebrainz/frontend/templates/moderators/moderators.html
critiquebrainz/frontend/templates/review/delete_comment.html
critiquebrainz/frontend/templates/review/entity/base.html
critiquebrainz/frontend/templates/review/report.html

An ISE (500) was returned instead of the page “About” with the pull requests #488 and #489 not released yet.
* Replace curved single quotes `‘’` that were used instead of straight one `'` as string delimiter
* Replace straight single quotes `'` that were used instead of typographic apostrophe `’` in strings
* Replace straight single quotes `'` that were used instead of curved quotation marks `“”` in strings

Fix single quotes

---

.github/workflows/tests.yml

I noticed this test workflow has been consistently failing* even thought the testing step succeeds. The action that is supposed to publish the test results is failing due to permissions issues.
I'm now adding  the required permissions to allow the workflow to write checks and comments on pull requests, as well as updating to a newer version of the action.
* see failures like so: https://github.com/metabrainz/critiquebrainz/actions/runs/6559728119/job/17815889047?pr=494#step:9:31

Update CI unit tests results workflow

---

critiquebrainz/frontend/static/scripts/wysiwyg-editor.js
critiquebrainz/frontend/templates/common.html
critiquebrainz/frontend/templates/review/entity/comments.html
critiquebrainz/frontend/templates/review/modify/base.html
package-lock.json
package.json
webpack.config.js

Tackling this long-standing security ticket for SimpleMDE, which happens to be abandoned, and won't have these security issues fixed: https://tickets.metabrainz.org/browse/SEC-163
Instead, a drop-in replacement fork EasyMDE exists ! Woo !
I also tweaked the Webpack config to allow us to import css files (and not just less files) instead of loading the css from a CDN as it was done previously.
As a pretty strong positive side effect, after testing it seems like the editor's preview option is broken in production, and will be fixed by this upgrade.

Replace SimpleMDE library with EasyMDE

---

docker/uwsgi/uwsgi.ini

We are trying to resolve issues with uWSGI running in the CB docker containers, which fail with the error `bind(): Address already in use [core/socket.c line 769]`
See this discussion or some background: https://chatlogs.metabrainz.org/libera/metabrainz/2023-11-02/?msg=5243055&page=2
This mimics how we configure the artwork redirect container: https://github.com/metabrainz/artwork-redirect/blob/c632ecfda1c5d5037e20a341f992b35ea7cc5ab8/docker/prod/uwsgi.ini#L3

Change socket to http in uwsgi.ini

---

Dockerfile

To fix uWSGI and consul template errors, we need a newer version of consul template. So upgrade the base python image which comes with the newer version of consul template. Also, need to upgrade python to 3.11 and uWSGI to a compatible version as a result.

Upgrade base python image

---

docker/uwsgi/consul-template-uwsgi.conf
docker/uwsgi/uwsgi.ini

We fixed the `bind(): Address already in use [core/socket.c line 769]` error in LB using `exit-on-reload = true` in uWSGI configuration. However, this prevents graceful reloading.
I did some further investigation as noted in metabrainz/artwork-redirect#46 and have a better fix in mind now.
For the command field in exec block of consul template configuration, use array format. This executes the command directly without spawning a shell wrapper or setting a process group id. Both of which will interfere with forwarding signals to the uWSGI process.

Improve uWSGI and consul-template interactions on reloading

---

critiquebrainz/frontend/templates/footer.html

Point to the MB wiki page for all things communications

Update link to chatrooms in footer
