critiquebrainz/frontend/templates/search/results.html, critiquebrainz/frontend/templates/search/selector_results.html
Now the text can be clicked to open the respective links.
=> Added apt links to search results during review

critiquebrainz/frontend/templates/log/log_results.html
http://tickets.musicbrainz.org/browse/CB-206
=> Fixing CB-206

critiquebrainz/frontend/views/review.py
http://tickets.musicbrainz.org/browse/CB-200
=> CB-200: Use 403 instead of 404 for reviews that are hidden

critiquebrainz/frontend/views/mapping.py
Fixed the results from Spotify to show in the right order.
=> Fixed the results from Spotify to show in the right order.

critiquebrainz/frontend/views/mapping.py
Added a check if Spotify returned current album.
=> Added a check if spotify returned current album.

critiquebrainz/frontend/templates/artist.html, critiquebrainz/frontend/views/artist.py
[CB-196](http://tickets.musicbrainz.org/browse/CB-196) [GCI](https://codein.withgoogle.com/dashboard/task-instances/6192451874193408/?sp-page=1) 
Artist pages showed the same member multiple times, so I've added merging of these duplicate members and showing the list of attributes, periods for each member. Former members attributes are not shown, because periods list might be too long and it wouldn't look nicely together. 
**Current prototype screens:** (click the artist name to see the current view on CB)
Note: attribute names lists may have spaces before commas, it is solved now but it left on the screenshots.
[**Foo fighters**](https://critiquebrainz.org/artist/67f66c07-6e61-4026-ade5-7e782fad3a5d)
[**Drifters**](https://critiquebrainz.org/artist/9e2d3f58-0653-4007-bcb7-1746fcdd9363) …
=> CB-196 Artist pages show the same member multiple times

critiquebrainz/frontend/templates/macros.html
The [JIRA ticket](http://tickets.musicbrainz.org/browse/CB-172) talks about a different way of implementing the flash message system, but I felt that a lot of the places in the code will need to be changed for it, and maybe it wouldn't be worth it.
=> CB-172: Remove header from flash messages

docs/contrib/installation.rst
[JIRA Issue](http://tickets.musicbrainz.org/browse/CB-163)
=> CB-163: Add info about compiling styling into installation instructions

critiquebrainz/frontend/templates/navbar.html, critiquebrainz/frontend/views/login.py
Similar to: https://github.com/metabrainz/acousticbrainz-server/pull/153
=> Login / Logout now redirects you to the page you came from

admin/schema_changes/7.sql, critiquebrainz/data/model/review.py, critiquebrainz/frontend/__init__.py, critiquebrainz/frontend/external/musicbrainz.py, critiquebrainz/frontend/static/css/main.less, critiquebrainz/frontend/templates/entity_review.html, critiquebrainz/frontend/templates/macros.html, critiquebrainz/frontend/templates/navbar.html, critiquebrainz/frontend/templates/place.html, critiquebrainz/frontend/templates/review/edit.html, critiquebrainz/frontend/templates/review/entity/place.html, critiquebrainz/frontend/templates/review/modify/place.html, critiquebrainz/frontend/templates/review/write.html, critiquebrainz/frontend/templates/search/index.html, critiquebrainz/frontend/templates/search/results.html, critiquebrainz/frontend/templates/search/selector.html, critiquebrainz/frontend/templates/search/selector_results.html, critiquebrainz/frontend/views/place.py, critiquebrainz/frontend/views/search.py
Most of the work was done during GSoC. I've rebased the branch, and made some fixes.
The pull was open on Bitbucket but since that repo has been deleted, I am opening it here again.
=> Places Entity

critiquebrainz/frontend/__init__.py, critiquebrainz/frontend/templates/navbar.html, critiquebrainz/utils.py
[JIRA Ticket](http://tickets.musicbrainz.org/browse/CB-89)
=> CB-89: Fix language selector behaviour in presence of query string

critiquebrainz/frontend/templates/footer.html
Fixes minor issue of the language choices redirecting to weird links.
(https://tickets.metabrainz.org/projects/CB/issues/CB-223)
=> CB-223: Make language selector at the bottom work

critiquebrainz/data/model/review.py, critiquebrainz/data/model/user.py, critiquebrainz/frontend/views/index.py
Move total review count and user count functions from views to models.
=> Move review count and user count to models.

critiquebrainz/db/revision.py, critiquebrainz/db/revision_test.py, critiquebrainz/frontend/templates/review/compare.html, critiquebrainz/frontend/templates/review/revision_results.html, critiquebrainz/frontend/views/review.py
Migrate revision code off the SQLAlchemy ORM.
=> CB-230: Migrate revisions-related code off the ORM

critiquebrainz/data/model/review.py, critiquebrainz/frontend/static/styles/main.less, critiquebrainz/frontend/templates/review/entity/base.html, critiquebrainz/frontend/views/review.py
Show more reviews (randomly sorted) from the same author on the review page
only if the author has written other reviews. If the author has written only one review, the review 
page stays exactly the same.
When some user is signed in:
When no one has logged in:
Single review written:
=> CB-120: Show more reviews from the same author on review page

critiquebrainz/db/revision.py, critiquebrainz/db/revision_test.py, critiquebrainz/db/spam_report.py, critiquebrainz/frontend/templates/reports/reports_results.html, critiquebrainz/frontend/views/review.py
Add redirect using `revision id` to `review/revisions/rev` page and add links of `revision` buttons in `report_results` page.
=> Link "Read revision" buttons in reports page.

critiquebrainz/frontend/templates/review/entity/base.html, critiquebrainz/frontend/views/test/test_review.py
Imported `cover_art` macro in review/base.html to fix Internal Server Error on event review pages.
=> CB-250: Fix ISE on event review pages.

critiquebrainz/frontend/templates/review/entity/place.html
Some `places` which may have a `life_span` attribute, may not have a `begin` (year) attribute. For example, see review: https://critiquebrainz.org/review/51fae187-b852-453c-9262-678b825ec31f.
=> CB-251: Fix ISE on some place review pages.

critiquebrainz/frontend/templates/review/browse.html, critiquebrainz/frontend/views/review.py
It needs work on the UI but are the changes according to what the ticket was for?
=> CB-198: Filter "browse/view all reviews" by entity type

critiquebrainz/db/oauth_client.py, critiquebrainz/db/oauth_client_test.py, critiquebrainz/frontend/views/profile_apps.py, critiquebrainz/frontend/views/test/profile_apps.py
Added functions and tests to migrate code for `OAuthClient` model. Also, made changes to `frontend` for using migrated code.
=> CB-230: Migrate OAuth Client code off the ORM.

critiquebrainz/data/fixtures.py, critiquebrainz/db/license.py, critiquebrainz/db/license_test.py, critiquebrainz/db/revision_test.py, critiquebrainz/db/spam_report_test.py, critiquebrainz/db/users_test.py, critiquebrainz/db/vote_test.py, critiquebrainz/frontend/views/test/test_review.py, critiquebrainz/ws/review/views_test.py
Added function `license.create` and `license.delete` for creating and deleting licenses. Made changes in their usages accordingly.
=> CB-230: Migrate license related code off the ORM

critiquebrainz/db/moderation_log.py, critiquebrainz/db/moderation_log_test.py, critiquebrainz/frontend/views/log.py, critiquebrainz/frontend/views/review.py, critiquebrainz/frontend/views/user.py
Added functions `moderation_log.create` and `moderation_log.list_logs` and corresponding tests for managing logs.
=> CB-230: Migrate Moderation Log code off the ORM.

critiquebrainz/db/oauth_token.py, critiquebrainz/db/oauth_token_test.py, critiquebrainz/frontend/views/profile_apps.py, critiquebrainz/ws/oauth/provider.py, critiquebrainz/ws/oauth/views.py, critiquebrainz/ws/testing.py
Added functions `create`, `list_tokens`, `delete` and `get_scopes` for managing `OAuth Tokens`. Also, added corresponding tests.
=> CB-230: Migrate OAuth Token related code off the ORM

critiquebrainz/db/oauth_grant.py, critiquebrainz/db/oauth_grant_test.py, critiquebrainz/ws/oauth/provider.py, critiquebrainz/ws/oauth/views.py
Added `create` , `list_grants`, `delete` and `get_scopes` and corresponding tests for code releated to `OAuthGrant` model.
=> CB-230: Migrate OAuth Grant off the ORM

critiquebrainz/db/oauth_token.py, critiquebrainz/db/users.py, critiquebrainz/frontend/templates/profile/applications/index.html
Fixes error while showing authorized user applications. https://sentry.metabrainz.org/share/issue/342e32333839/
=> Fix error when showing authorized user applications.

critiquebrainz/db/users.py
Sorry for missing this in the initial PR.
=> Fix missing table name in function users.tokens

critiquebrainz/db/users_test.py
Added tests for db related functions: `db.users.tokens` and `db.users.clients` in `db/users_test.py`
=> Add tests for functions users.tokens and users.clients

critiquebrainz/db/review.py
*This also fixes issue https://tickets.metabrainz.org/browse/CB-258.*
=> General improvements and fixes for db.review module

Dockerfile, docker/push.sh
Also adds Git SHA environment variable for production images.
=> Add a script for pushing images to the Docker Hub

critiquebrainz/frontend/external/exceptions.py, critiquebrainz/frontend/external/spotify.py, critiquebrainz/frontend/external/spotify_test.py, critiquebrainz/frontend/views/mapping.py
This adds better error handling, type annotations, renaming, and a bunch of other minor improvements.
=> Refactor functions for accessing the Spotify API

critiquebrainz/db/review.py, critiquebrainz/frontend/templates/review/entity/base.html, critiquebrainz/ws/review/views.py
The function is supposed to return votes of a review in votes dictionary as mentioned in the comments.
So, created that and other necessary changes elsewhere.
=> Consolidate votes in a dict in db.review.get_by_id() function

critiquebrainz/db/avg_rating.py, critiquebrainz/db/avg_rating_test.py, critiquebrainz/db/exceptions.py, critiquebrainz/db/moderation_log_test.py, critiquebrainz/db/oauth_client_test.py, critiquebrainz/db/oauth_grant_test.py, critiquebrainz/db/oauth_token_test.py, critiquebrainz/db/review.py, critiquebrainz/db/review_test.py, critiquebrainz/db/revision.py, critiquebrainz/db/revision_test.py, critiquebrainz/db/spam_report_test.py, critiquebrainz/db/user.py, critiquebrainz/db/users_test.py, critiquebrainz/db/vote_test.py, critiquebrainz/frontend/login/__init__.py, critiquebrainz/ws/oauth/provider.py
Create db/avg_rating module for operations on avg_rating
=> CB-244: Rating data access functions

critiquebrainz/frontend/templates/index/guidelines.html, critiquebrainz/frontend/views/index.py, critiquebrainz/frontend/views/test/test_index.py
All of the content is copied from https://wiki.musicbrainz.org/How_to_write_Good_Critiquebrainz_Reviews without any modifications apart from conversion to HTML/Jinja.
=> CB-264: Publish review guidelines on the website

critiquebrainz/frontend/external/musicbrainz_db/place.py
Added wrapper `_get_place_by_gid` for calling `fetch_multiple_places` for a single `MBID`.
=> CB-231: Add wrapper for fetch_multiple_places for a single MBID

critiquebrainz/frontend/external/musicbrainz_db/event.py, critiquebrainz/frontend/external/musicbrainz_db/helpers.py, critiquebrainz/frontend/external/musicbrainz_db/includes.py, critiquebrainz/frontend/external/musicbrainz_db/serialize.py, critiquebrainz/frontend/external/musicbrainz_db/test_data.py, critiquebrainz/frontend/external/musicbrainz_db/tests/event_test.py, critiquebrainz/frontend/external/musicbrainz_db/utils.py, critiquebrainz/frontend/templates/event/entity.html, critiquebrainz/frontend/views/event.py
Added functions to use db access for entity: `event`. Some test related tasks are remaining.
=> CB-231: Use direct database access for entity: event

critiquebrainz/db/__init__.py, critiquebrainz/ws/parser.py, critiquebrainz/ws/review/views.py, critiquebrainz/ws/review/views_test.py
=> CB-244: Rating support in the API

critiquebrainz/frontend/static/gulpfile.js, critiquebrainz/frontend/static/scripts/wysiwyg-editor.js, critiquebrainz/frontend/static/styles/main.less, critiquebrainz/frontend/templates/review/modify/base.html, critiquebrainz/frontend/views/review.py, npm-shrinkwrap.json, package.json
[JIRA ticket](https://tickets.metabrainz.org/browse/CB-95).
This modifies `templates/review/modify/base.html` to use `SimpleMDE` for the review content editor.
Also, there are not nearly as many actual changes as the diff indicates - the changes to `npm-shrinkwrap.json` account for most of them.
=> CB-95: Use SimpleMDE as an editor for CritiqueBrainz

critiquebrainz/data/dump_manager.py, critiquebrainz/db/license.py, critiquebrainz/db/moderation_log.py, critiquebrainz/db/oauth_client.py, critiquebrainz/db/oauth_grant.py, critiquebrainz/db/oauth_token.py, critiquebrainz/db/review.py, critiquebrainz/db/revision.py, critiquebrainz/db/spam_report.py, critiquebrainz/db/users.py, critiquebrainz/db/vote.py, critiquebrainz/frontend/external/mbspotify.py, critiquebrainz/frontend/external/musicbrainz.py, critiquebrainz/frontend/external/musicbrainz_db/artist.py, critiquebrainz/frontend/external/musicbrainz_db/event.py, critiquebrainz/frontend/external/musicbrainz_db/utils.py, critiquebrainz/frontend/forms/review.py, critiquebrainz/frontend/login/__init__.py, critiquebrainz/frontend/views/__init__.py, critiquebrainz/frontend/views/index.py, critiquebrainz/frontend/views/place.py, critiquebrainz/frontend/views/release.py, critiquebrainz/frontend/views/release_group.py, critiquebrainz/frontend/views/test/test_review.py, critiquebrainz/ws/review/views.py, manage.py, pylintrc, requirements.txt
Presently, this https://github.com/PyCQA/pylint/issues/1609 issue causes the tests to fail with the present version of `pylint`.
=> CB-272: Update pylint version and fix the `Unused variable '__class__'` error for unit tests.

docs/intro.rst
This should make it a bit easier for people to set up the development environment.
=> Add note telling people about MusicBrainz sample dumps to docs

critiquebrainz/frontend/templates/review/modify/base.html
[Jira ticket](https://tickets.metabrainz.org/browse/CB-239)
Minor change - just added it before the "you can use markdown" message.
=> CB-239: Reference review style guide when writing a review

critiquebrainz/frontend/views/mapping.py
Changed way of fetching release group info in `mapping.py`. Also fixes https://sentry.metabrainz.org/share/issue/342e32383839/
=> CB-231: Retrieve release group data directly from db in mapping.py

critiquebrainz/frontend/views/review.py, critiquebrainz/frontend/views/test/test_review.py
https://tickets.metabrainz.org/browse/CB-268
=> CB-268: Update review only if contents are edited

critiquebrainz/frontend/__init__.py, critiquebrainz/frontend/views/test/test_index.py, requirements.txt
Also, add a test to ensure that it works
=> Initialize Flask-DebugToolbar correctly

critiquebrainz/db/review.py, critiquebrainz/db/review_test.py, critiquebrainz/frontend/external/musicbrainz_db/serialize.py, critiquebrainz/frontend/external/musicbrainz_db/special_entities.py, critiquebrainz/frontend/external/musicbrainz_db/tests/event_test.py, critiquebrainz/frontend/external/musicbrainz_db/tests/place_test.py, critiquebrainz/frontend/external/musicbrainz_db/tests/release_group_test.py, critiquebrainz/frontend/external/musicbrainz_db/utils.py
=> CB-269: Handle reviewed entities deleted in MB database

Dockerfile, docker/prod/uwsgi/uwsgi.service
=> CB-232: Add support for running cron jobs in prod

docs/intro.rst
Added the command to convert sample dumps into bz2. And some other minor changes.
=> Improve the setup docs a bit

Dockerfile, admin/config.sh.ctmpl, admin/functions.sh, admin/rsync-dump-files.sh, docker/prod/consul-template.conf, docker/prod/cron/jobs
Also add a new job for copying data over to the
ftp server
=> Fix cron jobs for data dumps

critiquebrainz/data/dump_manager.py
Added support for dumping and importing `avg_rating` table. Also, added column `rating` in revision table dumps.
=> CB-283: Add support for dumping and importing rating tables

critiquebrainz/frontend/templates/user/info.html
Added a statement to assure user that their email is private.
=> CB-297: Reassure user that their email is private

Dockerfile, docker/beta/uwsgi/uwsgi.ini, docker/beta/uwsgi/uwsgi.service, docker/push.sh
Add new uwsgi.ini and service files, use these according to deploy_env in the Dockerfile, make changes in push.sh.
=> Change Dockerfile and push.sh and add stuff for CB Beta

critiquebrainz/frontend/templates/index/index.html
Looks better than just the text currently present
on the site.
=> CB-292: Show a table for stats on the home page

docs/export.rst
=> CB-285: Fix commands to export dumps in docs

critiquebrainz/data/dump_manager.py, critiquebrainz/frontend/views/review.py
Refactor public function in `dump_manager.py` (Removing a lot of duplicate code) and using transaction for copying tables.
=> Refactor public function in dump_manager

critiquebrainz/frontend/templates/macros.html, critiquebrainz/frontend/templates/release_group/entity.html, critiquebrainz/frontend/templates/review/entity/release_group.html
=> CB-291: Call for action to MB for adding missing Cover arts. (on review and release group pages)

consul_config.py.ctmpl, critiquebrainz/frontend/views/moderators.py
This is to update beta to use postgres-slave too.
=> Merge production into master

manage.py
Reinitialize database using ``--force`` command.
=> CB-284: Add an option to reset tables and types to manage.py init_db

admin/schema_changes/10.sql, admin/sql/create_foreign_keys.sql, admin/sql/create_tables.sql, critiquebrainz/data/dump_manager.py, critiquebrainz/db/__init__.py, critiquebrainz/db/user.py, critiquebrainz/db/users.py, critiquebrainz/frontend/forms/profile.py, critiquebrainz/frontend/forms/review.py, critiquebrainz/frontend/templates/profile/edit.html, critiquebrainz/frontend/templates/review/modify/base.html, critiquebrainz/frontend/views/profile.py, critiquebrainz/frontend/views/review.py, critiquebrainz/frontend/views/test/test_profile.py
Presently, a user has to select license every time he/she writes a review. This will give them a preferred license which will be the default option in their review edit page.
Ticket Link: https://tickets.metabrainz.org/projects/CB/issues/CB-262
=> CB-262: Ability to change default license selected when writing a review

admin/schema_changes/11.sql, admin/sql/create_foreign_keys.sql, admin/sql/create_primary_keys.sql, admin/sql/create_tables.sql, admin/sql/drop_tables.sql, critiquebrainz/db/__init__.py
Add two tables, very similar to how it's done for reviews.
=> CB-295: Add tables to support comments on reviews in CB

critiquebrainz/db/comment.py, critiquebrainz/db/comment_revision.py, critiquebrainz/db/comment_test.py
Gonna rebase once the schema changes get merged.
=> CB-295: Add db functions to create, delete and update comments. 

critiquebrainz/frontend/__init__.py, critiquebrainz/frontend/forms/comment.py, critiquebrainz/frontend/templates/macros.html, critiquebrainz/frontend/templates/review/entity/base.html, critiquebrainz/frontend/views/comment.py, critiquebrainz/frontend/views/review.py, critiquebrainz/frontend/views/test/test_comment.py
There's lots of features to add still, but I think that this is work enough to release.
=> CB-295: Show comments on reviews and add ability to add comments.

requirements.txt
This fixes cache problems and upgrades Flask
=> Bump up brainzutils-python in requirements.txt

critiquebrainz/data/dump_manager.py, critiquebrainz/db/license.py, critiquebrainz/db/review.py, critiquebrainz/db/users.py
Make JSON Dumps in a transaction.
=> CB-298: Add transaction support for json dumps

critiquebrainz/data/dump_manager.py
Make public dumps in a single transaction.
=> CB-298: Add transaction support for public dumps

critiquebrainz/db/review.py, critiquebrainz/db/review_test.py
Filters out hidden reviews from popular reviews.
=> CB-302: No hidden reviews in popular reviews

critiquebrainz/db/avg_rating.py, critiquebrainz/db/avg_rating_test.py, critiquebrainz/db/review.py
Added code and tests to make average ratings exclude hidden reviews' ratings
=> CB-325: No hidden reviews' ratings in avg ratings

critiquebrainz/frontend/__init__.py, critiquebrainz/ws/__init__.py
Added code in webserver init file to wait for consul config file.
=> CB-299: Wait for consul config

critiquebrainz/frontend/templates/navbar.html
=> Fix the alignment errors for logged in users in the navbar

critiquebrainz/frontend/forms/comment.py, critiquebrainz/frontend/templates/review/delete.html, critiquebrainz/frontend/templates/review/delete_comment.html, critiquebrainz/frontend/templates/review/entity/base.html, critiquebrainz/frontend/views/comment.py, critiquebrainz/frontend/views/test/test_comment.py
* Added `comment.delete` view
* Added tests for `commen.delete` view
* Added template for `comment.delete` confirmation
* Improved template, tests for `comment.create` view
=> CB-303: Delete comments

critiquebrainz/frontend/templates/review/entity/release_group.html
https://tickets.metabrainz.org/browse/CB-344
=> CB-344: Make RG review header use join phrases

requirements.txt
Upgrading dependencies due to security issues.
=> Fix SEC issues by upgrading dependencies

npm-shrinkwrap.json, package.json
This PR updates lodash, jquery and bootstrap to newer versions in `npm_shrinkwrap.json` and `package.json`.
=> SEC-5: Update lodash, jquery and bootstrap 

critiquebrainz/frontend/templates/review/modify/write.html, critiquebrainz/frontend/views/review.py, docker/Dockerfile.test
https://tickets.metabrainz.org/browse/CB-357
=> CB-357: Artist review creation page title does not have artist name

critiquebrainz/frontend/templates/artist/entity.html, critiquebrainz/frontend/templates/event/entity.html, critiquebrainz/frontend/templates/label/entity.html, critiquebrainz/frontend/templates/place/entity.html, critiquebrainz/frontend/templates/release_group/entity.html, critiquebrainz/frontend/templates/work/entity.html, critiquebrainz/frontend/views/review.py, critiquebrainz/frontend/views/test/test_review.py
Do not raise BadRequest if both entity_id and entity_type are missing
=> CB-373: "Write a review" link in footer doesn't work

critiquebrainz/data/dump_manager.py
I was unable to test this fix because it requires the full MB data dump as well to display the website correctly. Also, the ticket does not explicitly mention it but I assumed that it meant to reset the revision table ID field because it of type SERIAL while other id columns have type uuid.
=> CB-381: Dump importer doesn't reset sequence values after importing items

docker/Dockerfile.test, docs/intro.rst, manage.py, test.sh
I was unable to find where this is done in the Docker but according to the comment on the ticket this fix seemed right.
JIRA: CB-296
=> CB-296: `init_postgres` function in `manage.py` doesn't work for the development environment

critiquebrainz/frontend/views/event.py, critiquebrainz/frontend/views/label.py, critiquebrainz/frontend/views/place.py, critiquebrainz/frontend/views/release_group.py, critiquebrainz/frontend/views/work.py
The issue was caused due to reviews that do not have a revision. #311 fixes the issue by creating the review and revision in the same transaction. This PR  improves the frontend check for this.
Jira: CB-372
=> CB-372: Error when trying to submit a rating twice

critiquebrainz/frontend/views/review.py, critiquebrainz/frontend/views/test/test_review.py
Redirect user to edit page if draft review exists
=> CB-368: Submitting a review, clicking back, and submitting again causes error

critiquebrainz/frontend/external/musicbrainz_db/artist.py, critiquebrainz/frontend/external/musicbrainz_db/entities.py, critiquebrainz/frontend/external/musicbrainz_db/event.py, critiquebrainz/frontend/external/musicbrainz_db/place.py, critiquebrainz/frontend/external/musicbrainz_db/release.py, critiquebrainz/frontend/external/musicbrainz_db/release_group.py
This supersedes #270.
JIRA: CB-356
=> CB-356: Implemented handling of deleted entities

critiquebrainz/frontend/forms/comment.py, critiquebrainz/frontend/forms/log.py, critiquebrainz/frontend/forms/profile.py, critiquebrainz/frontend/forms/profile_apps.py, critiquebrainz/frontend/forms/review.py
=> CB-386: Use InputRequired validator in forms instead of DataRequired

.github/workflows/codeql-analysis.yml
Enable code scanning to find vulnerabilities and errors in codebase.
=> Setup code scanning

critiquebrainz/frontend/templates/artist/entity.html, critiquebrainz/frontend/templates/common.html, critiquebrainz/frontend/templates/event/entity.html, critiquebrainz/frontend/templates/label/entity.html, critiquebrainz/frontend/templates/macros.html, critiquebrainz/frontend/templates/mapping/list.html, critiquebrainz/frontend/templates/place/entity.html, critiquebrainz/frontend/templates/recording/entity.html, critiquebrainz/frontend/templates/release_group/entity.html, critiquebrainz/frontend/templates/review/entity/artist.html, critiquebrainz/frontend/templates/review/entity/release_group.html, critiquebrainz/frontend/templates/search/results.html, critiquebrainz/frontend/templates/search/selector_results.html, critiquebrainz/frontend/templates/work/entity.html, critiquebrainz/frontend/views/artist.py, critiquebrainz/frontend/views/test/test_artist.py, critiquebrainz/frontend/views/test/test_rate.py
=> CB-270: Added rating support for artists

Dockerfile
See https://github.com/metabrainz/listenbrainz-server/pull/1427
=> Install postgresql-client from xenial repository to match base image

critiquebrainz/ws/oauth/views.py, critiquebrainz/ws/review/views.py, critiquebrainz/ws/user/views.py
This PR adds proper headers and an OPTIONS method to many of the API endpoints to CORS errors.
=> Fix CORS issues for some endpoints

critiquebrainz/db/oauth_token.py, critiquebrainz/ws/oauth/provider.py, critiquebrainz/ws/oauth/views.py
Should fix bunch of errors in sentry from accessing unavailable token (probably revoked by user?). 
https://sentry.metabrainz.org/metabrainz/critiquebrainz/issues/145691/
=> Check if access_token is None before accessing it

default_config.py
=> Add Hebrew Language

critiquebrainz/db/review.py, critiquebrainz/ws/review/test/views_test.py, critiquebrainz/ws/review/views.py, docker/docker-compose.test.yml, docs/api/endpoints.rst
=> CB-396: Add webservice parameter to return reviews with only text or ratings or both

critiquebrainz/db/review.py, critiquebrainz/frontend/templates/macros.html, critiquebrainz/frontend/templates/user/reviews.html, critiquebrainz/ws/review/test/views_test.py, critiquebrainz/ws/review/views.py
A missing translation and a bit of reformatting.
=> Some misc minor fixes

Dockerfile
=> Fix crontab permissions

critiquebrainz/frontend/views/artist.py, critiquebrainz/frontend/views/event.py, critiquebrainz/frontend/views/log.py, critiquebrainz/frontend/views/mapping.py, critiquebrainz/frontend/views/place.py, critiquebrainz/frontend/views/recording.py, critiquebrainz/frontend/views/release_group.py, critiquebrainz/frontend/views/reports.py, critiquebrainz/frontend/views/review.py, critiquebrainz/frontend/views/search.py, critiquebrainz/frontend/views/user.py, critiquebrainz/frontend/views/work.py
[CB:405](https://tickets.metabrainz.org/browse/CB-405): Added exception catching where the user input is getting converted to an integer.
=> CB-405: invalid literal for int() with base 10

critiquebrainz/data/utils.py
Should have been reverted in 754f5a71c6 but was missed
=> Use test config file in test request context

critiquebrainz/frontend/templates/artist/entity.html
Do not display None if start date not present
=> CB-361: Group member list shows None if relationship has end date and no start date

critiquebrainz/frontend/views/review.py, critiquebrainz/frontend/views/test/test_review.py
CB-392
I added an extra condition to check whether it is a draft while checking if the user has made any updates in its review.
=> CB-392-After Saving draft, cannot publish without making some change.

critiquebrainz/frontend/templates/review/delete.html, critiquebrainz/frontend/templates/review/delete_comment.html
[CB-430](https://tickets.metabrainz.org/projects/CB/issues/CB-430)
=> CB-430: Delete review button is missing some metadata

critiquebrainz/db/review.py, critiquebrainz/db/test/review_test.py, critiquebrainz/frontend/templates/review/browse.html, critiquebrainz/frontend/views/review.py, critiquebrainz/ws/review/test/views_test.py, critiquebrainz/ws/review/views.py
[CB-347](https://tickets.metabrainz.org/browse/CB-347) 
- Added sorting option on reviews page.
- Created new sort option `published_on_asc` in db.
=> CB-347: Allow users to browse reviews by new, old and other criteria

critiquebrainz/frontend/views/test/test_review.py, docker/docker-compose.test.yml, requirements.txt
One entity which was in schema 25 sample db is no longer present in
the new one, update the entity id
=> Upgrade to MB schema 27 and new version of mbdata and sample DB

critiquebrainz/frontend/external/relationships/place.py, critiquebrainz/frontend/templates/place/entity.html
On a Place page we would show the parent place that this place was a part of (backward place-place rel), but we wouldn't show the child places of this place.
Update parsing code and display to add this information
=> Show both forward and backward place-place rels (Parts and Part of)

critiquebrainz/frontend/templates/navbar.html, critiquebrainz/frontend/templates/search/index.html
- Require the user to enter something in the text box before presenting any results.
=> Nav Search Enhancement

critiquebrainz/frontend/external/notify_moderators.py
We updated BU, and in that PR I claimed that we used a list everywhere, but I guess I missed this one
=> Make sure that the recipient to send_email is a list

critiquebrainz/frontend/external/entities.py, critiquebrainz/frontend/templates/review/entity/recording.html
=> CB-440: Recording entity [unknown artist]

critiquebrainz/frontend/templates/index/about.html
Discussed at length on IRC, feedback welcome.
=> Adding Guidelines and link to CoC

.gitignore, critiquebrainz/frontend/external/bookbrainz.py, critiquebrainz/frontend/external/musicbrainz.py, critiquebrainz/frontend/templates/navbar.html, critiquebrainz/frontend/templates/search/index.html, critiquebrainz/frontend/templates/search/results.html, critiquebrainz/frontend/views/search.py
This PR adds the feature to allow user to search for Edition Group
=> Allow searching of Edition Group

critiquebrainz/ws/review/test/views_test.py, critiquebrainz/ws/review/views.py
This PR adds the average ratings count in the API.
=> feat: Return average ratings count in API

Dockerfile, Dockerfile.webpack, critiquebrainz/frontend/external/bookbrainz_db/test/literary_work_test.py, package-lock.json, package.json
This PR:
1. Fixes Failing tests
2. Upgrades to Node 20
3. Fixes the node `SCRIPT DEPRECATION WARNING` https://github.com/metabrainz/critiquebrainz/actions/runs/6082007492/job/16498874717#step:8:758
=> Fix failing tests and Migrate to Node 20

critiquebrainz/frontend/templates/bb_literary_work/entity.html
This PR fixes an incorrect variable name, causing error
=> Fix undefined variable

develop.sh, test.sh
See https://github.com/metabrainz/listenbrainz-server/pull/2184.
=> Make develop.sh and test.sh compatible with compose v2

admin/sql/clear_tables.sql, critiquebrainz/data/testing.py, critiquebrainz/data/utils.py, critiquebrainz/db/users.py, critiquebrainz/frontend/external/__init__.py, critiquebrainz/frontend/testing.py, critiquebrainz/frontend/views/review.py, critiquebrainz/frontend/views/test/test_artist.py, critiquebrainz/frontend/views/test/test_bb_author.py, critiquebrainz/frontend/views/test/test_oauth.py, critiquebrainz/frontend/views/test/test_review.py, critiquebrainz/frontend/views/test/test_user.py, critiquebrainz/testing.py, critiquebrainz/ws/__init__.py, critiquebrainz/ws/testing.py, requirements.txt
Remove unmaintained flask testing library and improve tests speed by clearing tables instead of dropping and recreating them between each test. These changes also help in upgrading the other flask dependencies.
=> Test Improvements
